/**
 * Prompt length caps — the wired prompt nobody can shorten.
 *
 * Many image and video models reject an over-long prompt at NanoGPT's route, before the provider is
 * called and before anything is charged:
 *
 *     400 {"error":"Your prompt is too long for Qwen Image 3. Please shorten it to 800 characters
 *          or less (current: 831 characters).","code":"prompt_too_long"}
 *
 * Free, but a dead end. In a graph the prompt is generated, not typed — an LLM node writes it and a
 * wire carries it into the image node — so "please shorten it" names something no caller controls
 * directly. For a headless or agent-driven run that's the whole workflow lost to a limit nobody was
 * told about.
 *
 * So: trim it to fit at a sentence boundary (fitPromptText) and REPORT it — a `prompt-trimmed`
 * progress event plus a process warning. A silent trim would be a bug; the report is what makes the
 * trim defensible. A cap we didn't know is learned from the live 400 (promptCapFromError) and kept
 * on the Workflow, so a retry states the limit instead of rediscovering it.
 *
 * What this deliberately does NOT do is edit the graph's own prompts to avoid the trim. An llm
 * node's system prompt goes to the model exactly as its author wrote it — injecting a "keep it
 * under N characters" directive on their behalf would silently change what their workflow produces.
 *
 * The image/video catalogs advertise no prompt limit at all (checked live 2026-07-26), hence the
 * probed table below. Audio's caps ARE catalog metadata (supported_parameters.max_chars) and are
 * read from the opt-in catalog instead — never listed here. Absent id = no cap found, or never
 * probed: unknown stays unconstrained, matching this library's permissive-gate rule everywhere else.
 *
 * Table generated by nanoodle's scripts/probe-prompt-caps.mjs; keep it in step with the copies in
 * nanoodle's index.html / play.html.
 */
import { catItem } from "./catalog.mjs";

export const PROMPT_CAPS = {
  generated: "2026-07-26",
  image: {
    "step-image-edit-2": 512,
    "qwen-image-3": 800,
    "z-image-turbo": 1200,
    "z-image-turbo-image-to-image": 1200,
    "z-image-turbo-lora": 1200,
    "2dn-pony-v2": 3000,
    "aniflatmix-anime": 3000,
    "aniflatmix-anime-sfwnsfw": 3000,
    "animagine-xl-31": 3000,
    "artiwaifu-diffusion": 3000,
    "atomix-xl": 3000,
    "boltning": 3000,
    "crystal-clear-xl": 3000,
    "crystal-clear-xlightning": 3000,
    "cyberrealistic-pony-v9": 3000,
    "cyberrealistic-xl": 3000,
    "dreamshaper-v1": 3000,
    "dreamshaper-xl": 3000,
    "fluently-xl": 3000,
    "flux-schnell": 3000,
    "hassaku-hentai": 3000,
    "hidream": 3000,
    "hidream-i1-fast": 3000,
    "ideogram:4@0": 3000,
    "infinite-illustrious": 3000,
    "juggernaut-lightning-flux": 3000,
    "juggernaut-pro-flux": 3000,
    "juggernaut-z": 3000,
    "miusmius-xl": 3000,
    "nsfw-gen-illustrious": 3000,
    "persona:376130@2456367": 3000,
    "pixelwave": 3000,
    "proteus": 3000,
    "prunaai:1@1": 3000,
    "qwen-image": 3000,
    "realpony-xl": 3000,
    "rev-animated": 3000,
    "riverflow-2-fast": 3000,
    "riverflow-2-max": 3000,
    "riverflow-2-standard": 3000,
    "runware:106@1": 3000,
    "runware:107@1": 3000,
    "stable-diffusion-xl-turbo": 3000,
    "stoiqo-new-reality": 3000,
    "wai-illustrious-sdxl": 3000,
  },
  video: {
    "minimax-hailuo-02": 2000,
    "lightricks-ltx-2-fast": 3000,
  },
};

// node type → which catalog its model comes from. Same split as estimate.mjs's PRICE_KIND, minus
// the types that take no prompt (transcribe) — chat is present so promptCap can say "no" for it:
// an LLM's own limit is tokens, and it is never the node being fitted.
const CAP_KIND = {
  llm: "chat", vision: "chat",
  image: "image", edit: "image", inpaint: "image",
  tvideo: "video", ivideo: "video", vedit: "video", lipsync: "video",
  music: "audio", remix: "audio", tts: "audio",
};

/**
 * The prompt character cap for a node, or null when the model has none / we don't know one.
 * `learned` (a Map of "kind:id" → cap) wins over the table: it came from this account hitting this
 * model today, and the table is a snapshot.
 */
export function promptCap(node, { catalog, learned } = {}) {
  const kind = CAP_KIND[node && node.type];
  const id = node && node.fields && node.fields.model;
  if (!kind || !id || kind === "chat") return null;
  const hit = learned && learned.get(kind + ":" + id);
  if (hit) return hit;
  if (kind === "audio") {
    const m = catItem(catalog, "audio", id);
    return (m && m.supported_parameters && m.supported_parameters.max_chars) || null;
  }
  return (PROMPT_CAPS[kind] && PROMPT_CAPS[kind][id]) || null;
}

/**
 * Cut to the last sentence end inside the cap, then the last word — never mid-word, and never below
 * 70% of the cap, where honouring a boundary would throw away more than the overflow did.
 */
export function fitPromptText(s, cap) {
  if (s.length <= cap) return s;
  const head = s.slice(0, cap), floor = Math.floor(cap * 0.7);
  const sent = Math.max(head.lastIndexOf(". "), head.lastIndexOf("! "), head.lastIndexOf("? "), head.lastIndexOf("\n"));
  if (sent >= floor) return head.slice(0, sent + 1).trim();
  const word = head.lastIndexOf(" ");
  return (word >= floor ? head.slice(0, word) : head).trim();
}

/**
 * Fit the prompt rather than lose the run to a 400 the caller can't act on. Returns
 * { fields, trimmed } — `trimmed` is non-null exactly when the caller owes the user an explanation,
 * and reporting it is not optional.
 */
export function withFittedPrompt(node, fields, opts = {}) {
  const cap = promptCap({ ...node, fields }, opts);
  const p = fields && fields.prompt;
  if (!cap || typeof p !== "string" || p.length <= cap) return { fields, trimmed: null };
  const prompt = fitPromptText(p, cap);
  return { fields: { ...fields, prompt }, trimmed: { from: p.length, to: prompt.length, cap } };
}

/**
 * NanoGPT phrases the rejection three ways (all live-verified 2026-07-26):
 *   {"error":"…Please shorten it to 800 characters or less (current: 831 characters).","code":"prompt_too_long"}
 *   {"error":{"message":"…512 characters or less…","code":"prompt_too_long"}}   ← nested
 *   {"error":"Prompt is too long. Please keep it under 3000 characters."}        ← no code at all
 * so match the sentence, not the envelope. "current: N" is deliberately unmatched — that's the
 * length we SENT, and learning it as the cap would grow the limit with every failure.
 */
const PROMPT_TOO_LONG_RE = /(?:shorten (?:it )?to|keep it under|at most|maximum of|limit of)\s*([\d,]{2,})\s*characters/i;

export const isPromptTooLong = (msg) => /prompt_too_long/i.test(String(msg || "")) || /prompt is too long/i.test(String(msg || ""));

export function promptCapFromError(msg) {
  const m = PROMPT_TOO_LONG_RE.exec(String(msg || ""));
  const v = m ? +m[1].replace(/,/g, "") : 0;
  return v > 0 ? v : null;
}

/** Bank a cap learned from a live rejection. Returns true when it's new information. */
export function learnPromptCap(learned, node, msg) {
  const cap = promptCapFromError(msg);
  const kind = CAP_KIND[node && node.type];
  const id = node && node.fields && node.fields.model;
  if (!cap || !kind || !id || learned.get(kind + ":" + id) === cap) return false;
  learned.set(kind + ":" + id, cap);
  return true;
}
